name: "Build and Push image to Docker Hub"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4